// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifbidnkycpzloiveytke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmYmlkbmt5Y3B6bG9pdmV5dGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjA3MTcsImV4cCI6MjA3MTM5NjcxN30.yShVKUxop3KKIWYYEkK8yALZJZMMnhLfDIxyjylNi5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});